project:
  type: website
#  post-render:
#    - "cp -r public/* _site/"
  render:
    - "!*.md"
    - "*.qmd"
    - "**/*.qmd"
    - "!content/posts/proj-fcc-report/*.qmd"
    - "!posts/09_fcc-data/index.qmd"
    - "!posts/09_fcc-data/proj-fcc-report/about.qmd"
    - "!posts/09_fcc-data/proj-fcc-report/fcc_funding.qmd"
    - "!posts/09_fcc-data/proj-fcc-report/FCC_provider_list.qmd"
    - "!posts/09_fcc-data/proj-fcc-report/hubb.qmd"
    - "!posts/09_fcc-data/proj-fcc-report/isp_eda.qmd"
    - "!posts/09_fcc-data/proj-fcc-report/metadata_raw_nbm.qmd"
    - "!posts/09_fcc-data/proj-fcc-report/ms-eda.qmd"
    - "!posts/09_fcc-data/proj-fcc-report/nbm_data.qmd"
    - "!posts/09_fcc-data/proj-fcc-report/ntia_test.qmd"
    - "!posts/09_fcc-data/proj-fcc-report/rdof.qmd"
    - "!posts/09_fcc-data/proj-fcc-report/road-eda.qmd"
    - "!posts/09_fcc-data/proj-fcc-report/zero_dl_up.qmd"

website:
  title: "Real~Currents"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: content/about/index.qmd
        text: About
      - href: content/dev/index.qmd
        text: Developer

format:
  html:
    theme:
      - darkly
      - src/custom.scss
    css: src/app/globals.css
    toc: true

