project:
  type: website

website:
  title: "Real~Currents"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - content/about.qmd

format:
  html:
    theme:
      - cosmo
      - src/styles/custom.scss
    css: src/styles/styles.css
    toc: true
