name: setup-node
description: "Setup Quarto/R 🔧"

runs:
  using: "composite"
  steps:
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    # From https://github.com/r-lib/actions/tree/v2-branch/setup-r
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1'

    - name: Install R package dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
        packages: |
          any::jsonlite
          any::png
          any::quarto
          any::renv
          any::rmarkdown

    #      - name: Install R dependencies with renv
    #        uses: r-lib/actions/setup-renv@v2
    #        with:
    #          cache-version: 1
